global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Tempo metrics
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  # Grafana Alloy metrics
  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]
    scrape_interval: 5s
